export const ArabicCharacterMap = {
  KeyA: { isolated: "ا", initial: "ا", medial: "ـا", final: "ـا", shift: "ِ" },
  KeyB: { isolated: "ب", initial: "بـ", medial: "ـبـ", final: "ـب", shift: "" },
  KeyC: { isolated: "ؤ", initial: "ؤ", medial: "ؤ", final: "ؤ", shift: "}" },
  KeyD: { isolated: "ي", initial: "يـ", medial: "ـيـ", final: "ـي", shift: "]" },
  KeyE: { isolated: "ث", initial: "ثـ", medial: "ـثـ", final: "ـث", shift: "ُ" },
  KeyF: { isolated: "ف", initial: "فـ", medial: "ـفـ", final: "ـف", shift: "[" },
  KeyG: { isolated: "ج", initial: "جـ", medial: "ـجـ", final: "ـج", shift: "" },
  KeyH: { isolated: "ه", initial: "هـ", medial: "ـهـ", final: "ـه", shift: "÷" },
  KeyI: { isolated: "ع", initial: "عـ", medial: "ـعـ", final: "ـع", shift: "‘" },
  KeyJ: { isolated: "ت", initial: "تـ", medial: "ـتـ", final: "ـت", shift: "ـ" },
  KeyK: { isolated: "ك", initial: "كـ", medial: "ـكـ", final: "ـك", shift: "،" },
  KeyL: { isolated: "ل", initial: "لـ", medial: "ـلـ", final: "ـل", shift: "/" },
  KeyM: { isolated: "م", initial: "مـ", medial: "ـمـ", final: "ـم", shift: "’" },
  KeyN: { isolated: "ن", initial: "نـ", medial: "ـنـ", final: "ـن", shift: "آ" },
  KeyO: { isolated: "خ", initial: "خـ", medial: "ـخـ", final: "ـخ", shift: "×" },
  KeyP: { isolated: "ح", initial: "حـ", medial: "ـحـ", final: "ـح", shift: "؛" },
  KeyQ: { isolated: "ض", initial: "ضـ", medial: "ـضـ", final: "ـض", shift: "َ" },
  KeyR: { isolated: "ر", initial: "ر", medial: "ر", final: "ر", shift: "ٌ" },
  KeyS: { isolated: "س", initial: "سـ", medial: "ـسـ", final: "ـس", shift: "ٍ" },
  KeyT: { isolated: "ط", initial: "طـ", medial: "ـطـ", final: "ـط", shift: "%" },
  KeyU: { isolated: "غ", initial: "غـ", medial: "ـغـ", final: "ـغ", shift: "إ" },
  KeyV: { isolated: "ظ", initial: "ظـ", medial: "ـظـ", final: "ـظ", shift: "{" },
  KeyW: { isolated: "ص", initial: "صـ", medial: "ـصـ", final: "ـص", shift: "ً" },
  KeyX: { isolated: "ء", initial: "ء", medial: "ء", final: "ء", shift: "ْ" },
  KeyY: { isolated: "ذ", initial: "ذ", medial: "ذ", final: "ذ", shift: "إ" },
  KeyZ: { isolated: "ز", initial: "ز", medial: "ز", final: "ز", shift: "~" },

  // Numbers and Symbols
  Digit1: { normal: "1", shift: "!" },
  Digit2: { normal: "2", shift: "@" },
  Digit3: { normal: "3", shift: "#" },
  Digit4: { normal: "4", shift: "$" },
  Digit5: { normal: "5", shift: "%" },
  Digit6: { normal: "6", shift: "^" },
  Digit7: { normal: "7", shift: "&" },
  Digit8: { normal: "8", shift: "*" },
  Digit9: { normal: "9", shift: ")" },
  Digit0: { normal: "0", shift: "(" },

  Minus: { normal: "-", shift: "_" },
  Equal: { normal: "=", shift: "+" },
  BracketLeft: { normal: "ج", shift: "<" },
  BracketRight: { normal: "د", shift: ">" },
  Backslash: { normal: "\\", shift: "|" },
  Semicolon: { normal: "ك", shift: ":" },
  Quote: { normal: "ط", shift: '"' },
  Backquote: { normal: "ذ", shift: "ّ" }, // Shadda (gemination)
  Comma: { normal: "و", shift: "," },
  Period: { normal: "ز", shift: "." },
  Slash: { normal: "ظ", shift: "؟" },

  // Space and Special Keys
  Space: { normal: " ", shift: " " },
  Enter: { normal: "\n", shift: "\n" },
  Tab: { normal: "\t", shift: "\t" },
};
