export const ArabicCharacterMap = {
  KeyH: { isolated: "ا", initial: "ا", medial: "ـا", final: "ـا", shift: "أ" },
  KeyF: { isolated: "ب", initial: "بـ", medial: "ـبـ", final: "ـب", shift: "[" },
  KeyJ: { isolated: "ت", initial: "تـ", medial: "ـتـ", final: "ـت", shift: "ـ" },
  KeyE: { isolated: "ث", initial: "ثـ", medial: "ـثـ", final: "ـث", shift: "ُ" },
  BracketLeft: { isolated: "ج", initial: "جـ", medial: "ـجـ", final: "ـج", shift: "<" },
  KeyP: { isolated: "ح", initial: "حـ", medial: "ـحـ", final: "ـح", shift: "؛" },
  KeyO: { isolated: "خ", initial: "خـ", medial: "ـخـ", final: "ـخ", shift: "×" },
  BracketRight: { isolated: "د", initial: "د", medial: "ـد", final: "ـد", shift: ">" },
  Backquote: { isolated: "ذ", initial: "ذ", medial: "ـذ", final: "ـذ", shift: "ّ" }, // Shadda (gemination)
  KeyV: { isolated: "ر", initial: "ر", medial: "ـر", final: "ـر", shift: "{" },
  Period: { isolated: "ز", initial: "ز", medial: "ـز", final: "ـز", shift: "." },
  KeyS: { isolated: "س", initial: "سـ", medial: "ـسـ", final: "ـس", shift: "ٍ" },
  KeyA: { isolated: "ش", initial: "شـ", medial: "ـشـ", final: "ـش", shift: "ِ" },
  KeyW: { isolated: "ص", initial: "صـ", medial: "ـصـ", final: "ـص", shift: "ً" },
  KeyQ: { isolated: "ض", initial: "ضـ", medial: "ـضـ", final: "ـض", shift: "َ" },
  Quote: { isolated: "ط", initial: "طـ", medial: "ـطـ", final: "ـط", shift: '"' },
  Slash: { isolated: "ظ", initial: "ظـ", medial: "ـظـ", final: "ـظ", shift: "؟" },
  KeyU: { isolated: "ع", initial: "عـ", medial: "ـعـ", final: "ـع", shift: "‘" },
  KeyY: { isolated: "غ", initial: "غـ", medial: "ـغـ", final: "ـغ", shift: "إ" },
  KeyT: { isolated: "ف", initial: "فـ", medial: "ـفـ", final: "ـف", shift: "لإ" },
  KeyR: { isolated: "ق", initial: "قـ", medial: "ـقـ", final: "ـق", shift: "ٌ" },
  Semicolon: { isolated: "ك", initial: "كـ", medial: "ـكـ", final: "ـك", shift: ":" },
  KeyG: { isolated: "ل", initial: "لـ", medial: "ـلـ", final: "ـل", shift: "لأ" },
  KeyL: { isolated: "م", initial: "مـ", medial: "ـمـ", final: "ـم", shift: "/" },
  KeyK: { isolated: "ن", initial: "نـ", medial: "ـنـ", final: "ـن", shift: "،" },
  KeyI: { isolated: "ه", initial: "هـ", medial: "ـهـ", final: "ـه", shift: "÷" },
  Comma: { isolated: "و", initial: "و", medial: "ـو", final: "ـو", shift: "," },
  KeyD: { isolated: "ي", initial: "يـ", medial: "ـيـ", final: "ـي", shift: "]" },
  KeyC: { isolated: "ؤ", initial: "ؤ", medial: "ـؤ", final: "ـؤ", shift: "}" },
  KeyZ: { isolated: "ئ", initial: "ئـ", medial: "ـئـ", final: "ـئ", shift: "~" },
  KeyX: { isolated: "ء", initial: "ء", medial: "ء", final: "ء", shift: "ْ" },
  KeyN: { isolated: "ى", initial: "ىـ", medial: "ـىـ", final: "ـى", shift: "آ" },

  // Numbers and Symbols
  Digit1: { normal: "١", shift: "!" },
  Digit2: { normal: "٢", shift: "@" },
  Digit3: { normal: "٣", shift: "#" },
  Digit4: { normal: "٤", shift: "$" },
  Digit5: { normal: "٥", shift: "%" },
  Digit6: { normal: "٦", shift: "^" },
  Digit7: { normal: "٧", shift: "&" },
  Digit8: { normal: "٨", shift: "*" },
  Digit9: { normal: "٩", shift: ")" },
  Digit0: { normal: "٠", shift: "(" },
  Minus: { normal: "-", shift: "_" },
  Equal: { normal: "=", shift: "+" },

  // Space and Special Keys
  Space: { normal: " ", shift: " " },
  Enter: { normal: "\n", shift: "\n" },
  Tab: { normal: "\t", shift: "\t" },
};
